name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: [windows-2019]
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-api-key: $({secrets.NugetAPIKey})
        nuget-version: '5.x'
    
    - name: Restore NuGet packages
      run: nuget restore Tekla.Extension.sln
    
    - name: Build the Solution
      run: msbuild Tekla.Extension.sln /p:Configuration=Release
    