
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create realease
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: $({github.ref})
          release_name: Realease $({github.ref})
          body: |
            Changes in this Realease

          draft: false
          prerelease: false
